### ISSUE TITLE
Corto is missing HTTP Router example

### ISSUE THREAD

**Issue by hendrenja** [cortoproject/examples#4]
Corto's HTTP router is a beautiful framework. It would be very helpful to build a small example for getting users started with creating HTTP Microservers in C(++).

**Comment by riktimmondal** [comment]
Can you help me to get started since i am a beginner,i would like to contribute

**Comment by hendrenja** [comment]
Hello @riktimmondal, I am about to submit a solution to this issue. If you would like, we can create a follow-up issue to extend the supported request types. 

My POST example is paired with a blog post describing how the service was implemented.
